export const experiences = [
  {id: 1, name: 'carpenter'},
  {id: 2, name: 'electrician'},
  {id: 3, name: 'blacksmith' },
  {id: 4, name: 'painter'},
  {id: 5, name: 'web developer'},
  {id: 6, name: 'nurse'},
  {id: 7, name: 'prime minister'},
  {id: 8, name: 'sheep hearder'},
  {id: 9, name: 'stone mason'},
  {id: 10, name: 'other'},
  {id: 11, name: 'king'},
  {id: 12, name: 'queen'},
  {id: 13, name: 'doctor'},
  {id: 14, name: 'engineer'},
  {id: 15, name: 'politician'},
  {id: 16, name: 'plumber'},
  {id: 17, name: 'gardener'},
  {id: 18, name: 'musician'},
  {id: 19, name: 'lawyer'},
  {id: 19, name: 'landscape architect'},
  {id: 20, name: 'architect'},
]
